// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PDFBuilder.Infrastructure.Persistence;

#nullable disable

namespace PDFBuilder.Infrastructure.Migrations;

[DbContext(typeof(TemplateDbContext))]
partial class TemplateDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("PDFBuilder.Core.Domain.Template", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<string>("LayoutJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("MetadataJson")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("Tags")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<int>("Version")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(1);

                b.HasKey("Id");

                b.HasIndex("Category");

                b.HasIndex("CreatedAt");

                b.HasIndex("IsActive");

                b.HasIndex("Name");

                b.ToTable("Templates", (string)null);
            });
#pragma warning restore 612, 618
    }
}
